// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlazmnrmoglpglhzsmgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sYXptbnJtb2dscGdsaHpzbWdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MDY1MjMsImV4cCI6MjA2Mzk4MjUyM30.HIZJMvJJF7mH9kRZtuRLmlKgWAuDqxMCtYyWPVapUX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);